# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_best_number <- function() {
    .Call(`_cmakepkg_rcpp_best_number`)
}

